name: Build iOS App

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # GitHub Actions needs macOS to build iOS apps

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 3: Build the app
      - name: Build iOS Project
        run: |
          xcodebuild -workspace Calculator.xcworkspace \
                     -scheme Calculator \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ${{ github.workspace }}/build/Calculator.xcarchive \
                     archive

      # Step 4: Export `.ipa` file
      - name: Export `.ipa` File
        run: |
          xcodebuild -exportArchive \
                     -archivePath ${{ github.workspace }}/build/Calculator.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath ${{ github.workspace }}/build/

      # Step 5: Save `.ipa` as an artifact
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/Calculator.ipa

          
